#!/usr/bin/env bash
set -e

dry_run=false

while getopts ":fcivd" opt; do
	case $opt in
		f)
			running_containers=$(docker ps -q)
			if [ -z "$running_containers" ]; then
				echo "No running containers found"
			fi
			;;
		c)
			stale_containers=$(docker ps -a -q)
			if [ -z "$stale_containers" ]; then
				echo "No stale containers found"
			fi
			;;
		i)
			untagged_images=$(docker images | egrep '^<none>' | awk '{print $3}')
			if [ -z "$untagged_images" ]; then
				echo "No untagged images found"
			fi
			;;
		v)
			dangling_volumes=$(docker volume ls -qf dangling=true)
			if [ -z "$dangling_volumes" ]; then
				echo "No dangling volumes found"
			fi
			;;
		d)
			dry_run=true
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			exit 1
			;;
	esac
done

if [ "$dry_run" = true ]; then
	if [ ! -z "$running_containers" ]; then
		echo "Running containers would be stopped: " $running_containers
	fi
	if [ ! -z "$stale_containers" ]; then
		echo "Stale containers would be removed: " $stale_containers
	fi
	if [ ! -z "$untagged_images" ]; then
		echo "Untagged images would be removed: " $untagged_images
	fi
else
	if [ ! -z "$running_containers" ]; then
		echo "Stopping running containers"
		docker kill $running_containers
	fi
	if [ ! -z "$stale_containers" ]; then
		echo "Deleting stale containers"
		docker rm -v $stale_containers
	fi
	if [ ! -z "$untagged_images" ]; then
		echo "Deleting untagged images"
		docker rmi $untagged_images
	fi
	if [ ! -z "$dangling_volumes" ]; then
		echo "Deleting dangling volumes"
		docker volume rm $dangling_volumes
	fi
fi

echo 'done.'
