#!/usr/bin/bash
set -e

dry_run=false
exec_cmd="$(basename $0)"

print_usage() {
	local opt
	local OPTARG
	local OPTIND
	local print_help=0
	while getopts ":h" opt; do
		case ${opt} in
			h)
				print_help=1
				;;
			\?)
				echo "Invalid argument: -$OPTARG" >&2
				return 1
				;;
		esac
	done
	shift $((OPTIND - 1))
	echo "Usage: $exec_cmd [-f] [-c] [-i] [-v] [-d]"
	if [ $print_help -ne 0 ]; then
		printf '	-f	%s\n' "Kill running containers"
		printf '	-c	%s\n' "Remove non-running (stale) containers"
		printf '	-i	%s\n' "Remove un-tagged images that don't have dependencies"
		printf '	-v	%s\n' "Remove dangling (unattached) volumes"
		printf '	-d	%s\n' "Dry run (print, but don't perform actions)"
		printf '	-h	%s\n' "Display help message"
		printf '	-p	%s\n' "Run 'docker system prune'"
	fi
}

system_prune=0

while getopts ":fcivdhp" opt; do
	case $opt in
		f)
			running_containers=$(docker ps -q)
			if [ -z "$running_containers" ]; then
				echo "No running containers found"
			fi
			;;
		c)
			stale_containers=$(docker ps -a -q)
			if [ -z "$stale_containers" ]; then
				echo "No stale containers found"
			fi
			;;
		i)
			untagged_images=$(docker images | egrep '^<none>' | awk '{print $3}')
			if [ -z "$untagged_images" ]; then
				echo "No untagged images found"
			fi
			;;
		v)
			dangling_volumes=$(docker volume ls -qf dangling=true)
			if [ -z "$dangling_volumes" ]; then
				echo "No dangling volumes found"
			fi
			;;
		d)
			dry_run=true
			;;
		h)
			print_usage -h
			exit 0
			;;
		p)
			system_prune=1
			;;
		\?)
			echo "Unknown argument: -$OPTARG" >&2
			print_usage >&2
			exit 1
			;;
	esac
done

if [ "$dry_run" = true ]; then
	if [ ! -z "$running_containers" ]; then
		echo "Running containers would be stopped: " $running_containers
	fi
	if [ ! -z "$stale_containers" ]; then
		echo "Stale containers would be removed: " $stale_containers
	fi
	if [ ! -z "$untagged_images" ]; then
		echo "Untagged images would be removed: " $untagged_images
	fi
	if [ ! -z "$dangling_volumes" ]; then
		echo "Dangling volumes would be removed: " $dangling_volumes
	fi
	if [ $system_prune -ne 0 ]; then
		printf 'Command would be run: "%s"\n' "docker system prune"
	fi
else
	if [ ! -z "$running_containers" ]; then
		echo "Stopping running containers"
		docker kill $running_containers
	fi
	if [ ! -z "$stale_containers" ]; then
		echo "Deleting stale containers"
		docker rm -v $stale_containers
	fi
	if [ ! -z "$untagged_images" ]; then
		echo "Deleting untagged images"
		docker rmi $untagged_images
	fi
	if [ ! -z "$dangling_volumes" ]; then
		echo "Deleting dangling volumes"
		docker volume rm $dangling_volumes
	fi
	if [ $system_prune -ne 0 ]; then
		echo 'Running "docker system prune"'
		docker system prune
	fi
fi

echo 'done.'
